"""
Generator for `app/services/_experience_prompts.py`.

Parses the source-of-truth matrix in `backend/prompts/experience_prompts.md`
(15 field categories x 6 experience levels, each with a Question Agent Prompt
and an Evaluator Agent Prompt) and emits a Python module of literal dicts plus
the lookup helpers and an import-time completeness guard.

Usage (from the `backend/` directory):

    python scripts/gen_experience_prompts.py

This keeps the project's convention intact: the markdown is the human-edited
source of truth, the generated `.py` holds the runtime literals. Edit the
markdown, re-run this script, and commit the regenerated module.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make `app...` importable when run from the `backend/` directory so we can
# validate category/level names against the canonical enums.
BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.db.models.enums import ExperienceLevel  # noqa: E402
from app.services._field_categories import FIELD_CATEGORIES  # noqa: E402

MD_PATH = BACKEND_ROOT / "prompts" / "experience_prompts.md"
OUT_PATH = BACKEND_ROOT / "app" / "services" / "_experience_prompts.py"

# Markdown level heading -> ExperienceLevel enum member.
_LEVEL_BY_HEADING = {
    "Internship": ExperienceLevel.internship,
    "Entry": ExperienceLevel.entry,
    "Mid": ExperienceLevel.mid,
    "Senior": ExperienceLevel.senior,
    "Staff": ExperienceLevel.staff,
    "Executive": ExperienceLevel.executive,
}

_QUESTION_LABEL = "**Question Agent Prompt**"
_EVALUATOR_LABEL = "**Evaluator Agent Prompt**"


def _parse(md_text: str) -> dict[str, dict[ExperienceLevel, dict[str, str]]]:
    """Parse the matrix markdown into {category: {level: {"question", "evaluator"}}}."""
    result: dict[str, dict[ExperienceLevel, dict[str, str]]] = {}
    category: str | None = None
    level: ExperienceLevel | None = None
    expecting: str | None = None  # "question" | "evaluator" | None

    for raw in md_text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("## "):
            heading = line[3:].strip()
            if heading not in _LEVEL_BY_HEADING:
                raise ValueError(f"Unknown experience-level heading: {heading!r}")
            level = _LEVEL_BY_HEADING[heading]
            expecting = None
            continue
        if line.startswith("# "):
            category = line[2:].strip()
            if category not in FIELD_CATEGORIES:
                raise ValueError(
                    f"Category heading {category!r} is not a known FieldCategory."
                )
            result.setdefault(category, {})
            level = None
            expecting = None
            continue
        if line == "---":
            expecting = None
            continue
        if line.startswith(_QUESTION_LABEL):
            expecting = "question"
            continue
        if line.startswith(_EVALUATOR_LABEL):
            expecting = "evaluator"
            continue
        if expecting and category and level is not None:
            cell = result[category].setdefault(level, {})
            # First content line after the label is the paragraph; ignore any
            # stray trailing lines (format is one paragraph per label).
            cell.setdefault(expecting, line)
            expecting = None

    return result


def _literal(text: str) -> str:
    """Return a safe Python string literal for the generated source."""
    # Triple-quoted is readable and the corpus has no embedded triple quotes,
    # but fall back to repr() if that assumption is ever violated.
    if '"""' not in text and not text.endswith('"') and "\\" not in text:
        return f'"""{text}"""'
    return repr(text)


_HEADER = '''\
"""
Experience-level guidance for the opening-question and evaluator agents.

AUTO-GENERATED by `backend/scripts/gen_experience_prompts.py` from
`backend/prompts/experience_prompts.md`. DO NOT EDIT BY HAND. To change the
text, edit the markdown and re-run the generator, then commit this file.

Layered on top of the field-category tailoring (`_star_opening_prompts.py` /
`_star_evaluator_rubric.py`): `build_star_opening_prompt` and
`build_star_system_instruction` append the matching paragraph below as an extra
section when the candidate's `ExperienceLevel` is known. When the level is None
(legacy users) or a cell is missing, the lookup returns "" and the section is
omitted — the same empty-omission discipline used elsewhere in the codebase.
"""

from __future__ import annotations

from app.db.models.enums import ExperienceLevel
from app.services._field_categories import FIELD_CATEGORIES, FieldCategory

__all__ = [
    "EXPERIENCE_QUESTION_GUIDANCE",
    "EXPERIENCE_EVALUATOR_GUIDANCE",
    "experience_question_block",
    "experience_evaluator_block",
]
'''

_FOOTER = '''

# Fail-loud completeness guard (mirrors `_star_evaluator_rubric.py`): every category x
# level cell must be present in both maps, else importing this module raises
# instead of silently dropping experience tailoring at request time.
def _check_complete(name: str, table: dict) -> None:
    missing = [
        (category, level.value)
        for category in FIELD_CATEGORIES
        for level in ExperienceLevel
        if level not in table.get(category, {})
    ]
    if missing:
        raise RuntimeError(
            f"{name} is missing entries for: {missing}. Every FieldCategory x "
            "ExperienceLevel pair must have guidance."
        )


_check_complete("EXPERIENCE_QUESTION_GUIDANCE", EXPERIENCE_QUESTION_GUIDANCE)
_check_complete("EXPERIENCE_EVALUATOR_GUIDANCE", EXPERIENCE_EVALUATOR_GUIDANCE)


def experience_question_block(
    category: FieldCategory | None,
    level: ExperienceLevel | None,
) -> str:
    """Return the question-agent guidance paragraph, or "" when not applicable.

    The `isinstance` guard means any value that isn't a real `ExperienceLevel`
    (None, a stray string, a stale enum) cleanly omits the section rather than
    raising — the same fail-soft / empty-omission posture used elsewhere.
    """
    if category is None or not isinstance(level, ExperienceLevel):
        return ""
    return EXPERIENCE_QUESTION_GUIDANCE.get(category, {}).get(level, "")


def experience_evaluator_block(
    category: FieldCategory | None,
    level: ExperienceLevel | None,
) -> str:
    """Return the evaluator-agent guidance paragraph, or "" when not applicable."""
    if category is None or not isinstance(level, ExperienceLevel):
        return ""
    return EXPERIENCE_EVALUATOR_GUIDANCE.get(category, {}).get(level, "")
'''


def _emit_table(var_name: str, kind: str, data: dict) -> str:
    lines = [f"{var_name}: dict[FieldCategory, dict[ExperienceLevel, str]] = {{"]
    for category in FIELD_CATEGORIES:
        if category not in data:
            raise ValueError(f"No cells parsed for category {category!r}")
        lines.append(f"    {category!r}: {{")
        for level in ExperienceLevel:
            cell = data[category].get(level, {})
            text = cell.get(kind)
            if not text:
                raise ValueError(
                    f"Missing {kind!r} prompt for {category!r} / {level.value}"
                )
            lines.append(f"        ExperienceLevel.{level.name}: {_literal(text)},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    md_text = MD_PATH.read_text(encoding="utf-8")
    data = _parse(md_text)

    question_table = _emit_table(
        "EXPERIENCE_QUESTION_GUIDANCE", "question", data
    )
    evaluator_table = _emit_table(
        "EXPERIENCE_EVALUATOR_GUIDANCE", "evaluator", data
    )

    out = (
        _HEADER
        + "\n\n"
        + question_table
        + "\n\n\n"
        + evaluator_table
        + "\n"
        + _FOOTER
    )
    OUT_PATH.write_text(out, encoding="utf-8")

    n_cells = sum(len(v) for v in data.values())
    print(
        f"Wrote {OUT_PATH.relative_to(BACKEND_ROOT)} "
        f"({len(data)} categories, {n_cells} cells)."
    )


if __name__ == "__main__":
    main()
