"""
Generator for `app/services/_motivation_fit_experience_prompts.py`.

Parses the source-of-truth matrix in
`backend/prompts/motivation_fit_experience_prompts.md` (5 ARCHETYPES x 6
experience levels, each with a Question Agent Prompt and an Evaluator Agent
Prompt) and emits a Python module of literal dicts plus the lookup helpers and an
import-time completeness guard.

This is the Motivation & Fit analogue of `gen_experience_prompts.py`; the only
structural difference is the outer axis is `Archetype` (from `_archetypes`),
not `FieldCategory` (M&F questions barely change by industry, so the level bar
is tailored per archetype).

Usage (from the `backend/` directory):

    python scripts/gen_mf_experience_prompts.py

Edit the markdown, re-run this script, and commit the regenerated module.
"""

from __future__ import annotations

import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.db.models.enums import ExperienceLevel  # noqa: E402
from app.services._archetypes import Archetype  # noqa: E402

MD_PATH = BACKEND_ROOT / "prompts" / "motivation_fit_experience_prompts.md"
OUT_PATH = (
    BACKEND_ROOT / "app" / "services" / "_motivation_fit_experience_prompts.py"
)

# Markdown archetype heading -> Archetype enum member.
_ARCHETYPE_BY_HEADING = {
    "Commitment-screened": Archetype.commitment_screened,
    "Mission-screened": Archetype.mission_screened,
    "Values-codified corporate": Archetype.values_codified,
    "Persuasion-demonstrated": Archetype.persuasion_demonstrated,
    "Environment-fit": Archetype.environment_fit,
}

# Markdown level heading -> ExperienceLevel enum member.
_LEVEL_BY_HEADING = {
    "Internship": ExperienceLevel.internship,
    "Entry": ExperienceLevel.entry,
    "Mid": ExperienceLevel.mid,
    "Senior": ExperienceLevel.senior,
    "Staff": ExperienceLevel.staff,
    "Executive": ExperienceLevel.executive,
}

_QUESTION_LABEL = "**Question Agent Prompt**"
_EVALUATOR_LABEL = "**Evaluator Agent Prompt**"


def _parse(md_text: str) -> dict[Archetype, dict[ExperienceLevel, dict[str, str]]]:
    """Parse the matrix markdown into {archetype: {level: {"question", "evaluator"}}}."""
    result: dict[Archetype, dict[ExperienceLevel, dict[str, str]]] = {}
    archetype: Archetype | None = None
    level: ExperienceLevel | None = None
    expecting: str | None = None  # "question" | "evaluator" | None

    for raw in md_text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("## "):
            heading = line[3:].strip()
            if heading not in _LEVEL_BY_HEADING:
                raise ValueError(f"Unknown experience-level heading: {heading!r}")
            level = _LEVEL_BY_HEADING[heading]
            expecting = None
            continue
        if line.startswith("# "):
            heading = line[2:].strip()
            if heading not in _ARCHETYPE_BY_HEADING:
                raise ValueError(
                    f"Archetype heading {heading!r} is not a known Archetype."
                )
            archetype = _ARCHETYPE_BY_HEADING[heading]
            result.setdefault(archetype, {})
            level = None
            expecting = None
            continue
        if line == "---":
            expecting = None
            continue
        if line.startswith(_QUESTION_LABEL):
            expecting = "question"
            continue
        if line.startswith(_EVALUATOR_LABEL):
            expecting = "evaluator"
            continue
        if expecting and archetype is not None and level is not None:
            cell = result[archetype].setdefault(level, {})
            cell.setdefault(expecting, line)
            expecting = None

    return result


def _literal(text: str) -> str:
    if '"""' not in text and not text.endswith('"') and "\\" not in text:
        return f'"""{text}"""'
    return repr(text)


_HEADER = '''\
"""
Experience-level guidance for the Motivation & Fit opening-question and evaluator
agents, keyed by ARCHETYPE x experience level (5 x 6 = 30 cells).

AUTO-GENERATED by `backend/scripts/gen_mf_experience_prompts.py` from
`backend/prompts/motivation_fit_experience_prompts.md`. DO NOT EDIT BY HAND. To
change the text, edit the markdown and re-run the generator, then commit this file.

Layered on top of the archetype tailoring (`_archetypes.py`) and the shared field
axis: `build_motivation_fit_opening_prompt` and
`build_motivation_fit_system_instruction` append the matching paragraph below as
an extra section when the candidate's `ExperienceLevel` is known. When the level
is None (legacy users) or a cell is missing, the lookup returns "" and the section
is omitted — the same empty-omission discipline used elsewhere in the codebase.
"""

from __future__ import annotations

from app.db.models.enums import ExperienceLevel
from app.services._archetypes import Archetype

__all__ = [
    "MF_EXPERIENCE_QUESTION_GUIDANCE",
    "MF_EXPERIENCE_EVALUATOR_GUIDANCE",
    "mf_experience_question_block",
    "mf_experience_evaluator_block",
]
'''

_FOOTER = '''
# Fail-loud completeness guard (mirrors `_experience_prompts.py`): every
# archetype x level cell must be present in both maps, else importing this module
# raises instead of silently dropping experience tailoring at request time.
def _check_complete(name: str, table: dict) -> None:
    missing = [
        (archetype.value, level.value)
        for archetype in Archetype
        for level in ExperienceLevel
        if level not in table.get(archetype, {})
    ]
    if missing:
        raise RuntimeError(
            f"{name} is missing entries for: {missing}. Every Archetype x "
            "ExperienceLevel pair must have guidance."
        )


_check_complete("MF_EXPERIENCE_QUESTION_GUIDANCE", MF_EXPERIENCE_QUESTION_GUIDANCE)
_check_complete("MF_EXPERIENCE_EVALUATOR_GUIDANCE", MF_EXPERIENCE_EVALUATOR_GUIDANCE)


def mf_experience_question_block(
    archetype: Archetype | None,
    level: ExperienceLevel | None,
) -> str:
    """Return the M&F question-agent guidance paragraph, or "" when not applicable."""
    if archetype is None or not isinstance(level, ExperienceLevel):
        return ""
    return MF_EXPERIENCE_QUESTION_GUIDANCE.get(archetype, {}).get(level, "")


def mf_experience_evaluator_block(
    archetype: Archetype | None,
    level: ExperienceLevel | None,
) -> str:
    """Return the M&F evaluator-agent guidance paragraph, or "" when not applicable."""
    if archetype is None or not isinstance(level, ExperienceLevel):
        return ""
    return MF_EXPERIENCE_EVALUATOR_GUIDANCE.get(archetype, {}).get(level, "")
'''


def _emit_table(var_name: str, kind: str, data: dict) -> str:
    lines = [f"{var_name}: dict[Archetype, dict[ExperienceLevel, str]] = {{"]
    for archetype in Archetype:
        if archetype not in data:
            raise ValueError(f"No cells parsed for archetype {archetype!r}")
        lines.append(f"    Archetype.{archetype.name}: {{")
        for level in ExperienceLevel:
            cell = data[archetype].get(level, {})
            text = cell.get(kind)
            if not text:
                raise ValueError(
                    f"Missing {kind!r} prompt for {archetype.value!r} / {level.value}"
                )
            lines.append(f"        ExperienceLevel.{level.name}: {_literal(text)},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    md_text = MD_PATH.read_text(encoding="utf-8")
    data = _parse(md_text)

    question_table = _emit_table(
        "MF_EXPERIENCE_QUESTION_GUIDANCE", "question", data
    )
    evaluator_table = _emit_table(
        "MF_EXPERIENCE_EVALUATOR_GUIDANCE", "evaluator", data
    )

    out = (
        _HEADER
        + "\n\n"
        + question_table
        + "\n\n\n"
        + evaluator_table
        + "\n"
        + _FOOTER
    )
    OUT_PATH.write_text(out, encoding="utf-8")

    n_cells = sum(len(v) for v in data.values())
    print(
        f"Wrote {OUT_PATH.relative_to(BACKEND_ROOT)} "
        f"({len(data)} archetypes, {n_cells} cells)."
    )


if __name__ == "__main__":
    main()
