"""
Sessions endpoints.

POST /api/v1/sessions             — start a new mock interview.
POST /api/v1/sessions/{id}/turns  — submit an answer audio blob for evaluation.
GET  /api/v1/sessions             — list the caller's completed sessions.
GET  /api/v1/sessions/{id}        — full session detail (session + turns).
"""

import asyncio
import json
import logging
import uuid
from datetime import datetime, timedelta, timezone
from uuid import UUID

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.sql import func

from app.core.auth import get_current_user_db
from app.db.models.enums import ExperienceLevel, SessionStatus, UserTier
from app.db.models.custom_question import CustomQuestion
from app.db.models.interview_session import InterviewSession
from app.db.models.interview_turn import InterviewTurn
from app.db.models.session_metrics import SessionMetrics
from app.db.models.user import User
from app.db.session import AsyncSessionLocal, get_db
from app.schemas.session import (
    CompanyBriefOut,
    DimensionAverages,
    ScoresOut,
    SessionCreateIn,
    SessionCreateOut,
    SessionDetailOut,
    SessionListItem,
    TurnOut,
    TurnSubmitOut,
)
from app.services import eval_registry
from app.services.company_research import (
    CompanyNotFoundError,
    research_company,
)
from app.services._field_prompts import FieldCategory
from app.services._injection import contains_injection
from app.services.daily_limit import (
    enforce_daily_limit,
    increment as daily_increment,
)
from app.services.coaching import generate_next_take
from app.services.delivery_consent import has_active_delivery_analytics_consent
from app.services.evaluator import EVAL_MODEL, EvaluatorOutput, evaluate_turn
from app.services.filler_words import count_filler_words, count_words, filler_rate_pct
from app.services.followup import generate_followup
from app.services.incidents import (
    log_error,
    log_injection_detected,
    log_interview_session_started,
    log_jd_mismatch_acknowledged,
)
from app.services.job_description import (
    check_job_description_match,
    looks_like_gibberish,
)
from app.services.moderation import check_moderation
from app.services.opening_question import generate_opening_question
from app.services.stt import transcribe_audio
from app.services.tts import DEFAULT_SPEED, synthesize_speech
from app.services.voice_pool import resolve_voice, voice_for_session

logger = logging.getLogger(__name__)

router = APIRouter()
_finalize_tasks: set[asyncio.Task[None]] = set()
_finalizing_sessions: set[UUID] = set()

# How long after the final answer was persisted we wait before the lazy
# reaper in `get_session` is allowed to re-spawn finalization. Comfortably
# longer than a normal finalize (turn-1 drain + ~30-40s evaluator) so a
# still-running finalizer is never raced; the per-session dedup set below is
# the primary guard within a process, this grace covers the multi-worker case.
_FINALIZE_REAP_AFTER = timedelta(seconds=90)


def _spawn_finalize(
    *,
    session_id: UUID,
    final_turn_id: UUID,
    category: FieldCategory | None,
    experience_level: ExperienceLevel | None,
    jd_summary: list[str] | None = None,
) -> None:
    """Spawn background finalization, deduped per session within this process.

    Holds a strong reference to the task (so it isn't GC'd mid-flight) and
    records the session id so the lazy reaper in `get_session` won't start a
    second, concurrent finalizer for a session this worker is already
    finishing — which would otherwise double the free-tier daily increment.
    """
    if session_id in _finalizing_sessions:
        return
    _finalizing_sessions.add(session_id)
    task = asyncio.create_task(
        _run_background_finalize(
            session_id=session_id,
            final_turn_id=final_turn_id,
            category=category,
            experience_level=experience_level,
            jd_summary=jd_summary,
        ),
        name=f"finalize-session-{session_id}",
    )
    _finalize_tasks.add(task)

    def _done(t: asyncio.Task[None]) -> None:
        _finalize_tasks.discard(t)
        _finalizing_sessions.discard(session_id)

    task.add_done_callback(_done)


# ── session creation ──────────────────────────────────────────────────────────

async def _persist_session_and_turn(
    db: AsyncSession,
    user: User,
    company: str,
    job_title: str,
    company_summary: str,
    opening_q: str,
    session_id: UUID,
    voice_id: str,
    experience_level: ExperienceLevel | None,
    roll_recent: bool = True,
    saved_question_id: UUID | None = None,
    speech_speed: float = DEFAULT_SPEED,
) -> UUID:
    """INSERT the session row + turn 1 atomically; return session.id.

    `session_id` is generated by the caller so the per-session voice
    selection (in `voice_pool`) can run BEFORE the row exists in the
    DB — this lets us TTS the opening question in parallel with the
    INSERT instead of serializing the two. `voice_id` is the resolved
    voice (either picked by the candidate or the deterministic
    fallback) and is persisted on the row so turn 2 reads the same
    value without re-deriving.

    `experience_level` is frozen onto the session here (from the user's live
    level on a fresh session, or a saved question's frozen level on
    re-practice) so `submit_turn` never reads the mutable user row.

    `roll_recent` gates the `recent_opening_questions` avoid-list write: True
    for fresh sessions (don't repeat questions across sessions), False for
    re-practice (the repeat is the whole point). `saved_question_id` links the
    session to a saved question at creation (re-practice path).
    """
    session = InterviewSession(
        id=session_id,
        user_id=user.id,
        company=company,
        job_title=job_title,
        company_summary=company_summary,
        status=SessionStatus.in_progress,
        started_at=func.now(),
        voice_id=voice_id,
        experience_level=experience_level,
        saved_question_id=saved_question_id,
        speech_speed=speech_speed,
    )
    db.add(session)
    await db.flush()

    turn = InterviewTurn(
        session_id=session.id,
        turn_number=1,
        question_text=opening_q,
        is_followup=False,
    )
    db.add(turn)

    # Roll this opening question into the avoid-list, newest-first, capped
    # at 3. Reassigned (not mutated in place) so SQLAlchemy dirty-tracking
    # picks it up; rides the same commit as the session + turn 1 INSERT.
    # Skipped on re-practice — that flow deliberately wants the same question.
    if roll_recent:
        user.recent_opening_questions = (
            [opening_q] + (user.recent_opening_questions or [])
        )[:3]

    await db.commit()
    await db.refresh(session)
    return session.id


@router.post("", response_model=SessionCreateOut, status_code=status.HTTP_201_CREATED)
async def create_session(
    body: SessionCreateIn,
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> SessionCreateOut:
    # Persist the client's latest timezone and enforce the free-tier daily cap
    # BEFORE moderation / research / TTS so a rate-limited request never spends
    # Serper, OpenRouter, or ElevenLabs credits. The counter itself only
    # advances at session finalization (`daily_increment` in the final-turn
    # branch of `submit_turn`).
    await enforce_daily_limit(db, user, timezone=body.timezone)

    # Deterministic prompt-injection gate on the two user-authored inputs that
    # feed company research + every downstream prompt. Free (no network) so it
    # runs BEFORE the billed moderation call below — an injected company /
    # job-title never reaches OpenAI moderation, Serper, OpenRouter, or
    # ElevenLabs. The delimiters + untrusted-data clause in `research_company`
    # are the recall layer for subtler attempts this high-precision regex skips.
    # STRICT gate (these are not interview answers): company + job_title are
    # short structured fields (also block a bare "API key"); the pasted job
    # description is long free-text (tolerates "API key rotation" prose). The
    # interview-turn transcript gate in `submit_turn` stays on the relaxed regex.
    if (
        contains_injection(body.company, strict=True, short_field=True)
        or contains_injection(body.job_title, strict=True, short_field=True)
        or contains_injection(body.job_description, strict=True)
    ):
        logger.info(
            "Session-create rejected by injection gate clerk_user_id=%s",
            user.clerk_user_id,
        )
        await log_injection_detected(
            source="sessions.company",
            text=(
                f"company={body.company!r} job_title={body.job_title!r} "
                f"job_description={body.job_description!r}"
            ),
            user=user,
            db=db,
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Input contains content that violates our usage policy.",
        )

    # Resolve an optional custom question up front (ownership 404) so an invalid
    # id fails fast — before any billed moderation / research / TTS spend. When
    # present it replaces the opening-question LLM call below; research still
    # runs so the follow-up + evaluator stay field-tailored.
    custom_question: CustomQuestion | None = None
    if body.custom_question_id is not None:
        custom_question = await db.get(CustomQuestion, body.custom_question_id)
        if custom_question is None or custom_question.user_id != user.id:
            raise HTTPException(
                status_code=404, detail="Custom question not found"
            )

    # Conservative gibberish gate on the pasted job description (only when one
    # was supplied). Free / local, so it runs before any billed call. A real
    # posting always passes; only obvious keysmash / symbol-soup is rejected.
    job_description = (body.job_description or "").strip()
    if job_description and looks_like_gibberish(job_description):
        logger.info(
            "Session-create rejected by JD gibberish gate clerk_user_id=%s",
            user.clerk_user_id,
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="That job description doesn't look valid. Please paste a real posting.",
        )

    # Pre-flight moderation on the two user-authored string inputs that
    # feed downstream LLM prompts. Blocking HERE means the content never
    # reaches Serper, OpenRouter, or ElevenLabs — so a malicious company
    # / job-title value can't cost us API-key reputation.
    # `company` is freshly typed in the setup form each session, so it always
    # needs moderation. `job_title` is NOT editable there — the frontend sends
    # the profile's `target_role`, already moderated at onboarding — so only
    # re-moderate it when a (direct-API) caller sends something other than that
    # vetted value. The remaining checks are independent, so run them
    # concurrently; each logs its incident in its own short-lived session, so the
    # request `db` is never touched concurrently.
    moderation_targets = [("sessions.company", body.company)]
    # `job_title` is the profile's active role by default, but a multi-role user
    # can start a session under any of their declared roles — all of which were
    # moderated at onboarding. Skip re-moderation when it matches ANY stored role.
    vetted_roles = user.target_roles or ([user.target_role] if user.target_role else [])
    if body.job_title not in vetted_roles:
        moderation_targets.append(("sessions.job_title", body.job_title))
    # The pasted job description is freshly user-supplied each session, so it
    # always needs moderation when present.
    if job_description:
        moderation_targets.append(("sessions.job_description", job_description))
    checks = await asyncio.gather(*(
        check_moderation(value, user=user, db=db, metadata={"source": source})
        for source, value in moderation_targets
    ))
    flagged = [
        (source, check.categories)
        for (source, _), check in zip(moderation_targets, checks)
        if check.flagged
    ]
    if flagged:
        logger.warning(
            "Session-create rejected by moderation clerk_user_id=%s flagged=%s",
            user.clerk_user_id, flagged,
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Input contains content that violates our usage policy.",
        )

    # Consistency guard: when a job description is pasted, confirm it lines up
    # with the candidate's declared industry / role / company before spending
    # any research credits. A clear mismatch (e.g. an IB posting against a SWE
    # profile) would confuse research + the opening-question generator, so we
    # block with a 409 and let the user explicitly continue (re-submitting with
    # `acknowledge_mismatch=true`). The check itself fails open — an LLM outage
    # never blocks a legitimate session.
    if job_description and not body.acknowledge_mismatch:
        match = await check_job_description_match(
            company=body.company,
            job_title=body.job_title,
            industry=user.industry,
            job_description=job_description,
        )
        if not match.match:
            logger.info(
                "Session-create JD mismatch clerk_user_id=%s reason=%r",
                user.clerk_user_id, match.reason,
            )
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={
                    "code": "job_description_mismatch",
                    "message": (
                        match.reason
                        or "Your target role, industry, or company doesn't "
                        "seem to match this job description."
                    ),
                },
            )
    elif job_description and body.acknowledge_mismatch:
        # The user re-submitted to override a flagged mismatch. Log it as a
        # warning for abuse visibility (the daily session cap bounds the actual
        # spend); the match LLM's reason isn't re-derived on this path.
        logger.info(
            "Session-create JD mismatch acknowledged clerk_user_id=%s",
            user.clerk_user_id,
        )
        await log_jd_mismatch_acknowledged(
            user=user,
            job_description=job_description,
            company=body.company,
            job_title=body.job_title,
            db=db,
        )

    try:
        brief = await research_company(
            body.company,
            body.job_title,
            user.experience_level,
            job_description=job_description or None,
        )
    except CompanyNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="We couldn't find that company. Please check the spelling.",
        )
    logger.info(
        "Session research complete: company=%r job_title=%r category=%r",
        body.company, body.job_title, brief.category,
    )
    if custom_question is not None:
        # The candidate picked their own question — skip the opening-question
        # LLM call entirely and use the (already-screened) custom text verbatim.
        opening_q = custom_question.question_text
    else:
        # Pass the candidate's recent opening questions (already loaded on the
        # user row by get_current_user_db — no extra query) as an avoid-list so
        # the generator doesn't repeat near-identical questions across sessions.
        opening_q = await generate_opening_question(
            user, brief, body.job_title,
            recent_questions=user.recent_opening_questions,
        )

    # Generate the session UUID up front so the voice can be resolved
    # before the row hits the DB. This lets TTS and the INSERT run in
    # parallel instead of waiting on the DB to hand back a
    # server-generated UUID.
    session_id = uuid.uuid4()
    # Honor the candidate's picker choice when valid, else a deterministic
    # per-session voice (see `resolve_voice`). The resolved voice is persisted
    # on the session row below so turn 2's TTS reads the same value.
    voice_id = resolve_voice(body.voice_id, session_id)

    audio_url, _ = await asyncio.gather(
        synthesize_speech(opening_q, voice_id=voice_id, speed=body.speech_speed),
        _persist_session_and_turn(
            db,
            user,
            company=body.company,
            job_title=body.job_title,
            company_summary=brief.model_dump_json(),
            opening_q=opening_q,
            session_id=session_id,
            voice_id=voice_id,
            experience_level=user.experience_level,
            # A custom question is a deliberate, reusable pick — don't push it
            # into the generation avoid-list (it isn't a generated question).
            roll_recent=custom_question is None,
            # Persist the chosen pace so turn 2's TTS matches turn 1.
            speech_speed=body.speech_speed,
        ),
    )
    await log_interview_session_started(
        db,
        user,
        session_id=session_id,
        metadata={
            "company": body.company,
            "job_title": body.job_title,
            "custom_question": custom_question is not None,
        },
    )

    return SessionCreateOut(
        session_id=session_id,
        summary=CompanyBriefOut(**brief.model_dump()),
        first_question=opening_q,
        first_question_audio_url=audio_url,
    )


# ── turn submission ───────────────────────────────────────────────────────────

# Hard cap on the uploaded answer audio. A 5-minute Opus/WebM clip is well
# under this (the frontend also auto-stops recording at the 5:00 mark), so the
# cap only ever trips on a malformed or malicious upload. Read in 1 MiB chunks
# and abort with 413 BEFORE the bytes can exhaust worker memory or get
# forwarded to ElevenLabs STT (burning quota). Mirrors onboarding's bounded
# résumé read (`_read_pdf_bounded`).
_MAX_AUDIO_BYTES = 50 * 1024 * 1024
_AUDIO_CHUNK_SIZE = 1024 * 1024


async def _read_audio_bounded(audio: UploadFile) -> bytes:
    """Read the full upload into memory, aborting with 413 past the cap."""
    buf = bytearray()
    while True:
        chunk = await audio.read(_AUDIO_CHUNK_SIZE)
        if not chunk:
            break
        buf.extend(chunk)
        if len(buf) > _MAX_AUDIO_BYTES:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail=(
                    f"Audio exceeds the {_MAX_AUDIO_BYTES // (1024 * 1024)} MB "
                    "limit. Please record a shorter answer."
                ),
            )
    return bytes(buf)


async def _insert_followup_turn(
    db: AsyncSession,
    session_id: UUID,
    parent_turn_id: UUID,
    question: str,
) -> None:
    """Insert turn 2 and flush (caller commits)."""
    db.add(InterviewTurn(
        session_id=session_id,
        turn_number=2,
        question_text=question,
        is_followup=True,
        parent_turn_id=parent_turn_id,
    ))
    await db.flush()


async def _followup_and_tts(
    question: str,
    transcript: str,
    voice_id: str,
    category: FieldCategory | None = None,
    role_signals: list[str] | None = None,
    sample_question_themes: list[str] | None = None,
    experience_level: ExperienceLevel | None = None,
    jd_summary: list[str] | None = None,
    speech_speed: float | None = None,
) -> tuple[str, str]:
    """Generate follow-up via Flash then TTS — runs before background eval.

    `voice_id` is the per-session voice from `voice_for_session(session.id)`
    — passed in (rather than recomputed here) to keep this helper a pure
    string-in / string-out function the caller can compose freely.

    `category`, `role_signals`, `sample_question_themes`, and
    `experience_level` are passed through to `generate_followup` so the
    follow-up prompt sees the same field / research / seniority context the
    opening question and evaluator already do. `jd_summary` (pasted-JD role
    facts, empty/None otherwise) is threaded the same way so the follow-up
    doesn't mischaracterize how the role operates — e.g. probing group
    collaboration for a solo role.
    """
    next_q = await generate_followup(
        question,
        transcript,
        category=category,
        role_signals=role_signals,
        sample_question_themes=sample_question_themes,
        experience_level=experience_level,
        jd_summary=jd_summary,
    )
    audio_url = await synthesize_speech(
        next_q, voice_id=voice_id, speed=speech_speed
    )
    return next_q, audio_url


# ── background evaluation ────────────────────────────────────────────────────

def _log_eval_scores(
    session_id: UUID,
    turn_id: UUID,
    category: FieldCategory | None,
    eval_out: EvaluatorOutput,
) -> None:
    """Emit a one-line INFO log with the field category and the 6 rubric
    scores returned by the evaluator. Aimed at smoke-testing field-tailored
    scoring end-to-end — grep the backend log for `Eval scored:` to confirm
    new sessions are running the new rubric."""
    logger.info(
        "Eval scored: session=%s turn=%s category=%r "
        "structure=%s problem_solving=%s impact=%s "
        "initiative=%s depth=%s delivery=%s",
        session_id, turn_id, category,
        eval_out.structure, eval_out.problem_solving, eval_out.impact,
        eval_out.initiative, eval_out.depth, eval_out.delivery,
    )


def _apply_eval_to_turn(turn: InterviewTurn, eval_out: EvaluatorOutput) -> None:
    """Copy evaluator output onto an InterviewTurn row (no commit)."""
    turn.structure_score       = eval_out.structure
    turn.problem_solving_score = eval_out.problem_solving
    turn.impact_score          = eval_out.impact
    turn.initiative_score      = eval_out.initiative
    turn.depth_score           = eval_out.depth
    turn.delivery_score        = eval_out.delivery
    turn.feedback              = eval_out.notes
    turn.feedback_detail       = eval_out.feedback_detail.model_dump()
    turn.ai_model_used         = EVAL_MODEL
    turn.evaluated_at          = datetime.utcnow()


async def _attach_next_take(
    eval_out: EvaluatorOutput,
    question: str,
    transcript: str,
    category: FieldCategory | None,
    experience_level: ExperienceLevel | None,
) -> None:
    """Run the focused coaching call and merge `next_take` into `eval_out`.

    Best-effort and grounded in the evaluator output that just landed. The
    coaching service already fails soft (returns None on any error), but we
    still guard here so a coaching problem can never block scoring/finalization.
    Mutates `eval_out.feedback_detail` in place so the downstream
    `_apply_eval_to_turn` persists it with the rest of the feedback.
    """
    try:
        next_take = await generate_next_take(
            question, transcript, eval_out,
            category=category, experience_level=experience_level,
        )
        if next_take is not None:
            eval_out.feedback_detail.next_take = next_take
    except Exception:  # noqa: BLE001
        logger.exception("next_take generation failed; leaving it unset")


async def _run_background_eval(
    session_id: UUID,
    turn_id: UUID,
    question: str,
    transcript: str,
    history: list[dict],
    cv_summary: dict | None,
    category: FieldCategory | None,
    experience_level: ExperienceLevel | None = None,
    jd_summary: list[str] | None = None,
) -> None:
    """Evaluate a turn after the request has already returned, then persist.

    Runs in its own AsyncSession because the request-scoped session that
    spawned this task is closed by the time the response leaves the wire.
    Failures are swallowed (logged) per the "skip_and_log" policy: turn 1
    just keeps its null scores and the finalize aggregator drops it from
    the per-dim average. Always unregisters from the eval registry in the
    `finally` block so a missed finalize doesn't leak the Task reference.

    `category` is the persisted `brief.category` for the session and selects
    the field-tailored rubric appendix inside `evaluate_turn`. `experience_level`
    is the candidate's seniority and selects the experience-tailored rubric
    appendix; both are passed explicitly because this task runs in a detached
    AsyncSession with no access to the request-scoped `user` row. `jd_summary`
    (pasted-JD role facts, `None`/empty otherwise) rides through the same way as
    calibration-only context for the evaluator.
    """
    try:
        async with AsyncSessionLocal() as db:
            try:
                eval_out = await evaluate_turn(
                    question, transcript, history,
                    cv_summary=cv_summary, category=category,
                    experience_level=experience_level,
                    jd_summary=jd_summary,
                )
                _log_eval_scores(session_id, turn_id, category, eval_out)
                await _attach_next_take(
                    eval_out, question, transcript, category, experience_level,
                )
                turn = await db.get(InterviewTurn, turn_id)
                if turn is None:
                    logger.warning(
                        "Background eval: turn %s vanished before scores landed; "
                        "skipping write.",
                        turn_id,
                    )
                    return
                _apply_eval_to_turn(turn, eval_out)
                await db.commit()
                logger.info(
                    "Background eval complete for session=%s turn=%s",
                    session_id, turn_id,
                )
            except Exception:
                # Roll the half-applied transaction back, then re-raise so the
                # outer except logs the traceback. Without rollback the next
                # use of this session inside the same `async with` would
                # surface a confusing "current transaction is aborted" error.
                await db.rollback()
                raise
    except Exception as exc:  # noqa: BLE001
        logger.exception(
            "Background eval failed for session=%s turn=%s; "
            "scores remain null and the turn will be excluded from the "
            "session aggregate.",
            session_id, turn_id,
        )
        await log_error(
            exc,
            metadata={
                "source": "background_eval",
                "session_id": session_id,
                "turn_id": turn_id,
            },
        )
    finally:
        eval_registry.discard(session_id)


async def _await_background_eval(session_id: UUID) -> None:
    """If turn 1's eval is still running, wait for it before finalizing.

    Idempotent: returns immediately when no task is registered (e.g. the
    background task already finished and called `discard`, or the demo
    happens to be running on a worker that restarted between turns and
    lost the in-memory registry — the inline fallback in `submit_turn`
    handles the latter case).
    """
    task = eval_registry.pop(session_id)
    if task is None:
        return
    if task.done():
        return
    logger.info(
        "Finalize: waiting for background eval to finish for session=%s",
        session_id,
    )
    # The task itself swallows exceptions, so this await never raises.
    await task


# ── session-completion aggregation ────────────────────────────────────────────

# Per-turn score tuple shape used by the aggregator below:
# (structure, problem_solving, impact, initiative, depth, delivery, fillers)
# All score slots are nullable so that a turn whose background eval
# failed (or was never run) cleanly drops out of the per-dim averages.
_TurnScores = tuple[
    float | None, float | None, float | None,
    float | None, float | None, float | None,
    int,
]


def _per_dimension_averages(turns: list[_TurnScores]) -> dict[str, float | None]:
    """Average each rubric dimension independently across `turns`.

    Each dimension is filtered for non-null values BEFORE averaging so:
      * `delivery` is averaged only over turns where the candidate had the
        camera on (legacy behavior — webcam declined ⇒ null).
      * Any of the 5 base scores can also be null when a turn's background
        eval crashed or never ran. Such a turn contributes null for the
        affected dim but still counts for the others (it shouldn't
        normally — eval is all-or-nothing — but this keeps the aggregator
        robust to partial failure).

    Returns null for a dimension when no turn produced a score for it; the
    history chart drops the line entirely instead of plotting zeros.
    """
    def _avg(values: list[float | None]) -> float | None:
        non_null = [v for v in values if v is not None]
        return round(sum(non_null) / len(non_null), 2) if non_null else None

    return {
        "structure":       _avg([t[0] for t in turns]),
        "problem_solving": _avg([t[1] for t in turns]),
        "impact":          _avg([t[2] for t in turns]),
        "initiative":      _avg([t[3] for t in turns]),
        "depth":           _avg([t[4] for t in turns]),
        "delivery":        _avg([t[5] for t in turns]),
    }


async def _upsert_session_metrics(
    db: AsyncSession,
    *,
    session_id: UUID,
    averages: dict[str, float | None],
    total_filler_word_count: int,
    total_word_count: int,
    overall_score: float | None,
    turns_evaluated: int,
) -> None:
    """Write (or replace) the cached aggregate row for a completed session.

    `session_metrics.session_id` has a UNIQUE constraint, so a re-finalize
    of the same session (shouldn't happen in the 2-turn flow but cheap
    insurance) deletes the existing row first rather than tripping IntegrityError.
    """
    existing = await db.execute(
        select(SessionMetrics).where(SessionMetrics.session_id == session_id)
    )
    row = existing.scalar_one_or_none()
    if row is not None:
        await db.delete(row)
        await db.flush()

    db.add(SessionMetrics(
        session_id=session_id,
        avg_structure=averages["structure"],
        avg_problem_solving=averages["problem_solving"],
        avg_impact=averages["impact"],
        avg_initiative=averages["initiative"],
        avg_depth=averages["depth"],
        avg_delivery=averages["delivery"],
        total_filler_word_count=total_filler_word_count,
        total_word_count=total_word_count,
        overall_score=overall_score,
        turns_evaluated=turns_evaluated,
    ))
    await db.flush()


async def _complete_session_from_turns(
    db: AsyncSession,
    *,
    session: InterviewSession,
    user: User,
    turns: list[InterviewTurn],
) -> bool:
    """Aggregate evaluated turns and mark the session completed.

    Turns whose evaluator failed keep nullable score columns and are excluded
    from the relevant averages, matching the existing finalization policy.

    Returns True if this call is the one that completed the session, False if
    another worker had already finalized it (see the conditional-UPDATE gate
    below) — the caller uses this to decide between commit and rollback.
    """
    all_turn_scores: list[_TurnScores] = [
        (
            float(t.structure_score)       if t.structure_score       is not None else None,
            float(t.problem_solving_score) if t.problem_solving_score is not None else None,
            float(t.impact_score)          if t.impact_score          is not None else None,
            float(t.initiative_score)      if t.initiative_score      is not None else None,
            float(t.depth_score)           if t.depth_score           is not None else None,
            float(t.delivery_score)        if t.delivery_score        is not None else None,
            int(t.filler_word_count or 0),
        )
        for t in turns
        if t.transcript_text is not None
    ]
    per_dim_avgs = _per_dimension_averages(all_turn_scores)
    total_fillers = sum(t[6] for t in all_turn_scores)
    total_words = sum(int(t.word_count or 0) for t in turns)
    flat_scores = [
        v for t in all_turn_scores for v in t[:6] if v is not None
    ]
    overall: float | None
    if flat_scores:
        overall = min(99.99, round(sum(flat_scores) / len(flat_scores) * 10, 2))
    else:
        overall = None

    turns_evaluated = sum(
        1 for t in all_turn_scores if any(v is not None for v in t[:6])
    )

    # Idempotent completion gate — cross-process safe.
    #
    # During a blue/green deploy cutover two finalizers can run for the same
    # session: the outgoing color's still-detached background task plus the
    # incoming color's lazy reaper. Both can read status=in_progress before
    # either commits, and the `_finalizing_sessions` dedup set is per-process so
    # it can't see across them. Flip the status with a conditional UPDATE
    # instead: under READ COMMITTED the second writer blocks on this row's lock,
    # then re-checks the predicate after the first commits, matches zero rows,
    # and bails — so the daily-counter bump and metrics write happen exactly
    # once no matter how many finalizers race.
    result = await db.execute(
        update(InterviewSession)
        .where(
            InterviewSession.id == session.id,
            InterviewSession.status == SessionStatus.in_progress,
        )
        .values(
            status=SessionStatus.completed,
            ended_at=func.now(),
            overall_score=overall,
        )
    )
    if result.rowcount == 0:
        logger.info(
            "Session %s already finalized by another worker; skipping metrics "
            "upsert and daily increment.",
            session.id,
        )
        return False

    # Mirror the committed row onto the in-memory ORM object for consistency.
    session.status        = SessionStatus.completed
    session.overall_score = overall

    await _upsert_session_metrics(
        db,
        session_id=session.id,
        averages=per_dim_avgs,
        total_filler_word_count=total_fillers,
        total_word_count=total_words,
        overall_score=overall,
        turns_evaluated=turns_evaluated,
    )

    if user.tier == UserTier.free:
        await daily_increment(db, user)

    return True


async def _run_background_finalize(
    session_id: UUID,
    final_turn_id: UUID,
    category: FieldCategory | None,
    experience_level: ExperienceLevel | None = None,
    jd_summary: list[str] | None = None,
) -> None:
    """Evaluate the final turn and complete the session after the request returns."""
    try:
        async with AsyncSessionLocal() as db:
            session = await db.get(InterviewSession, session_id)
            if session is None:
                logger.warning(
                    "Background finalize: session %s vanished before completion",
                    session_id,
                )
                return
            if session.status == SessionStatus.completed:
                return
            if session.status != SessionStatus.in_progress:
                logger.warning(
                    "Background finalize: session=%s status=%s; skipping",
                    session_id,
                    session.status,
                )
                return

            user = await db.get(User, session.user_id)
            if user is None:
                logger.warning(
                    "Background finalize: user %s vanished for session=%s",
                    session.user_id,
                    session_id,
                )
                return

            # Let turn 1's detached eval finish if this worker still knows
            # about it. Missing/stale registry entries are handled by the
            # inline fallback below.
            await _await_background_eval(session_id)

            turns_result = await db.execute(
                select(InterviewTurn)
                .where(InterviewTurn.session_id == session_id)
                .order_by(InterviewTurn.turn_number)
            )
            turns = list(turns_result.scalars().all())

            for turn in turns:
                if turn.transcript_text is None or turn.structure_score is not None:
                    continue

                if turn.id != final_turn_id:
                    logger.warning(
                        "Background finalize inline-eval fallback for "
                        "session=%s turn=%s",
                        session_id,
                        turn.id,
                    )

                history = [
                    {"question": t.question_text, "transcript": t.transcript_text}
                    for t in turns
                    if (
                        t.id != turn.id
                        and t.transcript_text is not None
                        and t.turn_number < turn.turn_number
                    )
                ]
                inline_cv = turn.cv_summary if isinstance(turn.cv_summary, dict) else None
                try:
                    eval_out = await evaluate_turn(
                        turn.question_text,
                        turn.transcript_text,
                        history,
                        cv_summary=inline_cv,
                        category=category,
                        experience_level=experience_level,
                        jd_summary=jd_summary,
                    )
                    _log_eval_scores(session_id, turn.id, category, eval_out)
                    await _attach_next_take(
                        eval_out,
                        turn.question_text,
                        turn.transcript_text,
                        category,
                        experience_level,
                    )
                    _apply_eval_to_turn(turn, eval_out)
                except Exception as exc:  # noqa: BLE001
                    logger.exception(
                        "Background finalize eval failed for session=%s turn=%s; "
                        "this turn will be excluded from the session aggregate.",
                        session_id,
                        turn.id,
                    )
                    await log_error(
                        exc,
                        user=user,
                        db=db,
                        metadata={
                            "source": "background_finalize",
                            "session_id": session_id,
                            "turn_id": turn.id,
                        },
                    )

            completed = await _complete_session_from_turns(
                db,
                session=session,
                user=user,
                turns=turns,
            )
            if completed:
                await db.commit()
                logger.info("Background finalize complete for session=%s", session_id)
            else:
                # Lost the finalize race to another worker (deploy-cutover
                # overlap). Discard our redundant re-evaluation instead of
                # committing it over the turn rows the winner already wrote.
                await db.rollback()
    except Exception as exc:  # noqa: BLE001
        logger.exception(
            "Background finalize failed for session=%s; session remains in_progress.",
            session_id,
        )
        await log_error(
            exc,
            metadata={
                "source": "background_finalize",
                "session_id": session_id,
            },
        )


@router.post("/{session_id}/turns", response_model=TurnSubmitOut)
async def submit_turn(
    session_id: UUID,
    audio: UploadFile = File(...),
    # Browser-computed webcam analytics (see `faceHeuristics.ts` on the
    # frontend). JSON-encoded; missing when the candidate declined camera.
    # Parse failures degrade gracefully to the 5-score path rather than 400.
    cv_summary: str | None = Form(None),
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> TurnSubmitOut:
    # 1. Load session — verify ownership.
    session = await db.get(InterviewSession, session_id)
    if not session or session.user_id != user.id:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.status != SessionStatus.in_progress:
        raise HTTPException(status_code=400, detail="Session is not in progress")

    if cv_summary and not has_active_delivery_analytics_consent(user):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "Delivery analytics consent is required before camera-derived "
                "delivery summaries can be submitted."
            ),
        )

    # 1a. Pull the persisted brief's category so we can hand it to the
    # evaluator and get field-tailored scoring. Legacy sessions persisted
    # before categorization existed produce `category=None`, which the
    # evaluator handles by falling back to the default-category prompt.
    brief_out = _parse_company_summary(session.company_summary)
    category: FieldCategory | None = brief_out.category if brief_out else None
    # Role facts distilled from a pasted JD (empty for Serper / no-JD sessions).
    # Threaded into the follow-up and evaluator as calibration-only context so
    # they don't mischaracterize how the role operates (e.g. probing group
    # collaboration for a solo role).
    jd_summary: list[str] | None = brief_out.jd_summary if brief_out else None
    # The candidate's seniority tailors the evaluator rubric alongside the
    # field category. Read from the SESSION (frozen at create time), NOT the
    # live user row: this keeps turn 1 and turn 2 on the same rubric even if
    # the user edits their profile mid-session, and keeps re-practices of a
    # saved question apples-to-apples after a profile change. None for legacy
    # rows created before this column existed; the evaluator omits the
    # experience appendix in that case.
    experience_level = session.experience_level

    # 2. Find the current unanswered turn (question exists, transcript is NULL)
    #    and LOCK it. `with_for_update(skip_locked=True)` is what closes the
    #    double-submit race: two concurrent POSTs for the same answer (double
    #    click, retry, two tabs) used to both read this row before either wrote
    #    a transcript — many `await`s pass before the commit in step 6 — so both
    #    sailed through to a billed evaluator call. Now the first request holds a
    #    row lock for the rest of the transaction; the second's `skip_locked`
    #    SELECT skips the locked row and gets nothing back.
    result = await db.execute(
        select(InterviewTurn)
        .where(
            InterviewTurn.session_id == session_id,
            InterviewTurn.transcript_text.is_(None),
        )
        .order_by(InterviewTurn.turn_number)
        .limit(1)
        .with_for_update(skip_locked=True)
    )
    current_turn = result.scalar_one_or_none()
    if current_turn is None:
        # No row available — but distinguish "genuinely no pending turn" (all
        # turns answered) from "the pending turn is locked by a sibling request
        # that's mid-flight". A plain (non-locking) re-check tells them apart so
        # we return the right status: a concurrent submit gets 409 (the client
        # should not retry), an already-complete session keeps the old 400.
        pending_exists = await db.scalar(
            select(InterviewTurn.id)
            .where(
                InterviewTurn.session_id == session_id,
                InterviewTurn.transcript_text.is_(None),
            )
            .limit(1)
        )
        if pending_exists is not None:
            raise HTTPException(
                status_code=409,
                detail="This answer is already being processed.",
            )
        raise HTTPException(status_code=400, detail="No pending turn for this session")

    # 3. Transcribe. Bounded read so an oversized upload is rejected with 413
    #    before it can OOM the worker or be sent to ElevenLabs STT.
    audio_bytes = await _read_audio_bounded(audio)
    transcript = await transcribe_audio(audio_bytes, audio.filename or "audio.webm")

    # 3a-pre. Deterministic prompt-injection gate. Free (no network) so it runs
    # BEFORE the billed moderation call: a transcript carrying an injection
    # marker never reaches moderation, the evaluator, or the DB. The pending turn
    # is left untouched (transcript still NULL) so the candidate simply
    # re-records — same UX as the moderation reject below. "violates our usage
    # policy" wording is load-bearing: the frontend maps it to the re-record
    # message in `Practice.tsx`.
    if contains_injection(transcript):
        logger.info(
            "Turn rejected by injection gate for session=%s turn=%s",
            session_id, current_turn.id,
        )
        await log_injection_detected(
            source="sessions.transcript",
            text=transcript,
            user=user,
            session_id=session_id,
            db=db,
            metadata={"turn_id": current_turn.id},
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "Your answer contains content that violates our usage policy. "
                "Please re-record and try again."
            ),
        )

    # 3a. Moderation pre-check on the transcript. Running BEFORE we persist
    # the row or spawn any LLM call means flagged content never reaches
    # OpenRouter / downstream providers and never lands in `interview_turns`.
    # The user gets a clean 422 instead of a scored turn; they can retry
    # with different content on the same still-pending turn.
    transcript_check = await check_moderation(
        transcript,
        user=user,
        db=db,
        session_id=session_id,
        metadata={
            "source": "turn.transcript",
            "session_id": session_id,
            "turn_id": current_turn.id,
        },
    )
    if transcript_check.flagged:
        logger.info(
            "Turn rejected by moderation for session=%s turn=%s categories=%s",
            session_id, current_turn.id, transcript_check.categories,
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "Your answer contains content that violates our usage "
                "policy. Please re-record and try again."
            ),
        )

    # 4. Filler words (regex ground truth per CLAUDE.md) + total word count
    #    (denominator for the filler rate).
    filler_count, filler_breakdown = count_filler_words(transcript)
    word_count = count_words(transcript)

    # 5. Collect prior evaluated turns for history context.
    prior_result = await db.execute(
        select(InterviewTurn)
        .where(
            InterviewTurn.session_id == session_id,
            InterviewTurn.transcript_text.isnot(None),
        )
        .order_by(InterviewTurn.turn_number)
    )
    prior_turns = prior_result.scalars().all()
    history = [
        {"question": t.question_text, "transcript": t.transcript_text}
        for t in prior_turns
    ]

    # 6. Parse webcam analytics sidecar if present. Failing closed (None)
    # keeps the turn viable; the evaluator just skips the delivery score.
    parsed_cv_summary: dict | None = None
    if cv_summary:
        try:
            loaded = json.loads(cv_summary)
            if isinstance(loaded, dict):
                parsed_cv_summary = loaded
            else:
                logger.warning("cv_summary payload was not a JSON object; ignoring")
        except json.JSONDecodeError as exc:
            logger.warning("cv_summary JSON parse failed: %s", exc)

    # 7. Hardcoded 2-turn rule (CLAUDE.md): turn 2 is always final.
    is_final = current_turn.turn_number >= 2

    # 8a. Persist transcript + filler counts BEFORE doing evaluator work.
    #     Background tasks mutate this same row; persisting now means they
    #     always find a transcript to evaluate against and the row is durable
    #     even if a task crashes.
    current_turn.transcript_text       = transcript
    current_turn.cv_summary            = parsed_cv_summary
    current_turn.filler_word_count     = filler_count
    current_turn.filler_word_breakdown = filler_breakdown
    current_turn.word_count            = word_count

    # 8b. Branch: non-final returns the follow-up; final returns immediately
    #     after spawning session finalization below.
    if not is_final:
        # Only wait for follow-up + TTS. Evaluation is spawned as a detached
        # task that writes scores to the DB later.
        # Voice was resolved at session-create time and persisted on
        # `session.voice_id`, so turn 2's audio always sounds like the
        # same interviewer who asked turn 1 even after a refresh.
        # Legacy rows (created before the column existed) fall back to
        # the old deterministic-random derivation from session.id —
        # which would have given the same answer at session-create
        # time, so the behavior is unchanged for those rows too.
        turn_voice_id = session.voice_id or voice_for_session(session.id)
        next_q, next_audio_url = await _followup_and_tts(
            current_turn.question_text,
            transcript,
            turn_voice_id,
            category=category,
            role_signals=brief_out.role_signals if brief_out else None,
            sample_question_themes=(
                brief_out.sample_question_themes if brief_out else None
            ),
            experience_level=experience_level,
            jd_summary=jd_summary,
            # Frozen at create time (None on legacy rows → tts default),
            # so turn 2 plays at the pace the candidate chose for turn 1.
            speech_speed=(
                float(session.speech_speed)
                if session.speech_speed is not None
                else None
            ),
        )
        await _insert_followup_turn(db, session_id, current_turn.id, next_q)
        # Commit BEFORE registering the background task so the bg task's
        # fresh AsyncSession sees the persisted transcript on its first
        # query. Without this, there's a tiny race where the task could
        # start evaluating an empty transcript_text.
        await db.commit()

        bg_task = asyncio.create_task(
            _run_background_eval(
                session_id=session_id,
                turn_id=current_turn.id,
                question=current_turn.question_text,
                transcript=transcript,
                history=history,
                cv_summary=parsed_cv_summary,
                category=category,
                experience_level=experience_level,
                jd_summary=jd_summary,
            ),
            name=f"eval-session-{session_id}-turn-{current_turn.turn_number}",
        )
        eval_registry.register(session_id, bg_task)

        return TurnSubmitOut(
            transcript=transcript,
            scores=None,
            feedback=None,
            feedback_detail=None,
            filler_word_count=filler_count,
            filler_word_breakdown=filler_breakdown,
            next_question=next_q,
            next_question_audio_url=next_audio_url,
            is_final=False,
            evaluation_pending=True,
        )

    # 8c. Final turn: persist immediately, then complete scoring/aggregation
    #     in the background so the user can enter Results without waiting on
    #     the evaluator. The session remains `in_progress` until the task
    #     writes metrics and flips it to `completed`. `updated_at` is stamped
    #     here as the "final answer committed" clock the lazy reaper in
    #     `get_session` measures its grace period against (the column has no
    #     onupdate, so nothing else moves it between create and now).
    session.updated_at = datetime.utcnow()
    await db.commit()

    _spawn_finalize(
        session_id=session_id,
        final_turn_id=current_turn.id,
        category=category,
        experience_level=experience_level,
        jd_summary=jd_summary,
    )

    return TurnSubmitOut(
        transcript=transcript,
        scores=None,
        feedback=None,
        feedback_detail=None,
        filler_word_count=filler_count,
        filler_word_breakdown=filler_breakdown,
        next_question=None,
        next_question_audio_url=None,
        is_final=True,
        evaluation_pending=True,
    )


# ── history routes ───────────────────────────────────────────────────────────

# Hard cap on `GET /sessions` rows. The history page renders a chart + table
# inline, so paging UI is overkill for the demo — 50 most-recent completed
# sessions is well past anything a user will rack up during the hackathon.
_HISTORY_LIMIT = 50


def _averages_from_metrics(m: SessionMetrics | None) -> DimensionAverages:
    """Adapt the cached metrics row to the wire-format averages object."""
    if m is None:
        return DimensionAverages()
    return DimensionAverages(
        structure=m.avg_structure,
        problem_solving=m.avg_problem_solving,
        impact=m.avg_impact,
        initiative=m.avg_initiative,
        depth=m.avg_depth,
        delivery=m.avg_delivery,
    )


def _parse_company_summary(raw: str | None) -> CompanyBriefOut | None:
    """Decode the persisted JSON brief back into the wire-format model.

    Returns None on missing or malformed payloads so a single bad row in
    history doesn't 500 the whole detail screen.
    """
    if not raw:
        return None
    try:
        return CompanyBriefOut.model_validate_json(raw)
    except Exception as exc:  # noqa: BLE001
        logger.warning("company_summary parse failed: %s", exc)
        return None


@router.get("", response_model=list[SessionListItem])
async def list_sessions(
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> list[SessionListItem]:
    """Return the caller's completed sessions, newest first.

    Per-dimension averages are read from the cached `session_metrics` row
    populated when the session finalized. Sessions that finished BEFORE
    that cache existed (legacy rows) come back with all averages = null;
    the frontend chart simply skips them.
    """
    result = await db.execute(
        select(InterviewSession, SessionMetrics)
        .outerjoin(
            SessionMetrics,
            SessionMetrics.session_id == InterviewSession.id,
        )
        .where(
            InterviewSession.user_id == user.id,
            InterviewSession.status == SessionStatus.completed,
        )
        .order_by(InterviewSession.created_at.desc())
        .limit(_HISTORY_LIMIT)
    )
    rows: list[SessionListItem] = []
    for session, metrics in result.all():
        rows.append(SessionListItem(
            id=session.id,
            company=session.company,
            job_title=session.job_title,
            status=session.status.value,
            overall_score=session.overall_score,
            started_at=session.started_at,
            ended_at=session.ended_at,
            created_at=session.created_at,
            turns_evaluated=metrics.turns_evaluated if metrics else 0,
            total_filler_word_count=(
                metrics.total_filler_word_count if metrics else None
            ),
            filler_word_rate=filler_rate_pct(
                metrics.total_filler_word_count if metrics else None,
                metrics.total_word_count if metrics else None,
            ),
            averages=_averages_from_metrics(metrics),
        ))
    return rows


def _maybe_reap_stuck_session(
    session: InterviewSession,
    turns: list[InterviewTurn],
) -> None:
    """Lazily recover a session left `in_progress` by a dead finalizer.

    The final-turn POST persists the transcript and hands scoring to a
    detached `_run_background_finalize` task. If the worker that spawned it
    dies before it commits (deploy, crash, OOM) — or the task itself raised
    and left the session un-finalized — the row stays `in_progress` forever:
    there is no cron sweeper. Recover opportunistically on read.

    Only fires once the final answer is durably persisted and the grace
    window has elapsed, and re-uses `_spawn_finalize`'s per-session dedup so
    it can never run alongside a finalizer this worker is already driving.
    `_run_background_finalize` is itself idempotent — it no-ops on a session
    that's since completed and only evaluates still-unscored turns — so a
    spurious re-spawn is harmless.
    """
    if session.status != SessionStatus.in_progress:
        return
    # Final answer committed? (2-turn rule: turn 2 carries the last answer.)
    final_turn = max(turns, key=lambda t: t.turn_number, default=None)
    if (
        final_turn is None
        or final_turn.turn_number < 2
        or final_turn.transcript_text is None
    ):
        return
    # Still within the window where a normal finalizer is expected to finish.
    # `updated_at` comes back tz-aware from Postgres (timestamptz); normalize to
    # naive UTC so it subtracts cleanly against naive `utcnow()`.
    last_activity = session.updated_at
    if last_activity.tzinfo is not None:
        last_activity = last_activity.astimezone(timezone.utc).replace(tzinfo=None)
    if datetime.utcnow() - last_activity < _FINALIZE_REAP_AFTER:
        return
    if session.id in _finalizing_sessions:
        return

    logger.warning(
        "Lazy-reaping stuck session=%s (in_progress, last activity %s); "
        "re-spawning finalization.",
        session.id,
        session.updated_at,
    )
    brief = _parse_company_summary(session.company_summary)
    _spawn_finalize(
        session_id=session.id,
        final_turn_id=final_turn.id,
        category=brief.category if brief else None,
        experience_level=session.experience_level,
        jd_summary=brief.jd_summary if brief else None,
    )


@router.get("/{session_id}", response_model=SessionDetailOut)
async def get_session(
    session_id: UUID,
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> SessionDetailOut:
    """Full session payload: session row + ordered turns + cached metrics.

    Ownership check happens BEFORE we fetch turns so an unauthorized
    request can't probe for another user's row counts via timing.
    """
    session = await db.get(InterviewSession, session_id)
    if session is None or session.user_id != user.id:
        raise HTTPException(status_code=404, detail="Session not found")

    turns_result = await db.execute(
        select(InterviewTurn)
        .where(InterviewTurn.session_id == session_id)
        .order_by(InterviewTurn.turn_number)
    )
    turns = list(turns_result.scalars().all())

    # Self-heal a session whose background finalizer never completed. This
    # read returns the still-`in_progress` payload as usual; the re-spawned
    # task flips it to `completed` out of band, and the client's poll picks
    # up the scores on a subsequent fetch.
    _maybe_reap_stuck_session(session, turns)

    metrics_result = await db.execute(
        select(SessionMetrics).where(SessionMetrics.session_id == session_id)
    )
    metrics = metrics_result.scalar_one_or_none()

    turn_outs = [
        TurnOut(
            id=t.id,
            turn_number=t.turn_number,
            question_text=t.question_text,
            transcript_text=t.transcript_text,
            is_followup=t.is_followup,
            scores=ScoresOut(
                # `0` is a valid evaluator score, so null must round-trip as
                # null — not coerced to 0 — otherwise the UI can't tell an
                # unevaluated turn from a 0/10 score, and the per-session
                # average gets dragged down by phantom zeros. The frontend
                # renders an "Evaluation Failed" placeholder for null rows.
                structure=int(t.structure_score) if t.structure_score is not None else None,
                problem_solving=int(t.problem_solving_score) if t.problem_solving_score is not None else None,
                impact=int(t.impact_score) if t.impact_score is not None else None,
                initiative=int(t.initiative_score) if t.initiative_score is not None else None,
                depth=int(t.depth_score) if t.depth_score is not None else None,
                delivery=int(t.delivery_score) if t.delivery_score is not None else None,
            ),
            feedback=t.feedback,
            feedback_detail=t.feedback_detail,
            filler_word_count=t.filler_word_count or 0,
            filler_word_breakdown=t.filler_word_breakdown or {},
            filler_word_rate=filler_rate_pct(t.filler_word_count, t.word_count),
            evaluated_at=t.evaluated_at,
            created_at=t.created_at,
        )
        for t in turns
    ]

    return SessionDetailOut(
        id=session.id,
        company=session.company,
        job_title=session.job_title,
        status=session.status.value,
        overall_score=session.overall_score,
        started_at=session.started_at,
        ended_at=session.ended_at,
        created_at=session.created_at,
        summary=_parse_company_summary(session.company_summary),
        turns=turn_outs,
        averages=_averages_from_metrics(metrics),
        total_filler_word_count=(
            metrics.total_filler_word_count if metrics else None
        ),
        filler_word_rate=filler_rate_pct(
            metrics.total_filler_word_count if metrics else None,
            metrics.total_word_count if metrics else None,
        ),
        turns_evaluated=metrics.turns_evaluated if metrics else 0,
        saved_question_id=session.saved_question_id,
    )
