"""
Sessions endpoints.

POST /api/v1/sessions             — start a new mock interview.
POST /api/v1/sessions/{id}/turns  — submit an answer audio blob for evaluation.
GET  /api/v1/sessions             — list the caller's completed sessions.
GET  /api/v1/sessions/{id}        — full session detail (session + turns).
"""

import asyncio
import json
import logging
import uuid
from datetime import datetime
from uuid import UUID

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.sql import func

from app.core.auth import get_current_user_db
from app.db.models.enums import SessionStatus
from app.db.models.interview_session import InterviewSession
from app.db.models.interview_turn import InterviewTurn
from app.db.models.session_metrics import SessionMetrics
from app.db.models.user import User
from app.db.session import AsyncSessionLocal, get_db
from app.schemas.session import (
    CompanyBriefOut,
    DimensionAverages,
    ScoresOut,
    SessionCreateIn,
    SessionCreateOut,
    SessionDetailOut,
    SessionListItem,
    TurnOut,
    TurnSubmitOut,
)
from app.services import eval_registry
from app.services.company_research import CompanyBrief, research_company
from app.services.evaluator import EVAL_MODEL, EvaluatorOutput, evaluate_turn
from app.services.filler_words import count_filler_words
from app.services.followup import generate_followup
from app.services.opening_question import generate_opening_question
from app.services.stt import transcribe_audio
from app.services.tts import synthesize_speech
from app.services.voice_pool import is_valid_voice_id, voice_for_session

logger = logging.getLogger(__name__)

router = APIRouter()


# ── session creation ──────────────────────────────────────────────────────────

async def _persist_session_and_turn(
    db: AsyncSession,
    user: User,
    body: SessionCreateIn,
    brief: CompanyBrief,
    opening_q: str,
    session_id: UUID,
    voice_id: str,
) -> UUID:
    """INSERT the session row + turn 1 atomically; return session.id.

    `session_id` is generated by the caller so the per-session voice
    selection (in `voice_pool`) can run BEFORE the row exists in the
    DB — this lets us TTS the opening question in parallel with the
    INSERT instead of serializing the two. `voice_id` is the resolved
    voice (either picked by the candidate or the deterministic
    fallback) and is persisted on the row so turn 2 reads the same
    value without re-deriving.
    """
    session = InterviewSession(
        id=session_id,
        user_id=user.id,
        company=body.company,
        job_title=body.job_title,
        company_summary=brief.model_dump_json(),
        status=SessionStatus.in_progress,
        started_at=func.now(),
        voice_id=voice_id,
    )
    db.add(session)
    await db.flush()

    turn = InterviewTurn(
        session_id=session.id,
        turn_number=1,
        question_text=opening_q,
        is_followup=False,
    )
    db.add(turn)
    await db.commit()
    await db.refresh(session)
    return session.id


@router.post("", response_model=SessionCreateOut, status_code=status.HTTP_201_CREATED)
async def create_session(
    body: SessionCreateIn,
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> SessionCreateOut:
    brief = await research_company(body.company)
    opening_q = await generate_opening_question(user, brief, body.job_title)

    # Generate the session UUID up front so the voice can be resolved
    # before the row hits the DB. This lets TTS and the INSERT run in
    # parallel instead of waiting on the DB to hand back a
    # server-generated UUID.
    session_id = uuid.uuid4()
    # Resolve the voice in this priority order:
    #   1. Candidate's explicit pick from the start-form picker
    #      (validated against the public pool — unknown IDs would 404
    #      at ElevenLabs and burn quota, so we fall through silently
    #      instead of trusting client input).
    #   2. Deterministic-random voice derived from the session UUID,
    #      which gives roughly uniform coverage across the pool when
    #      the candidate skipped the picker.
    # Either way, the resolved voice is persisted on the session row
    # below so turn 2's TTS reads the same value without re-deriving.
    if body.voice_id and is_valid_voice_id(body.voice_id):
        voice_id = body.voice_id
    else:
        voice_id = voice_for_session(session_id)

    audio_url, _ = await asyncio.gather(
        synthesize_speech(opening_q, voice_id=voice_id),
        _persist_session_and_turn(
            db, user, body, brief, opening_q, session_id, voice_id,
        ),
    )

    return SessionCreateOut(
        session_id=session_id,
        summary=CompanyBriefOut(**brief.model_dump()),
        first_question=opening_q,
        first_question_audio_url=audio_url,
    )


# ── turn submission ───────────────────────────────────────────────────────────

async def _insert_followup_turn(
    db: AsyncSession,
    session_id: UUID,
    parent_turn_id: UUID,
    question: str,
) -> None:
    """Insert turn 2 and flush (caller commits)."""
    db.add(InterviewTurn(
        session_id=session_id,
        turn_number=2,
        question_text=question,
        is_followup=True,
        parent_turn_id=parent_turn_id,
    ))
    await db.flush()


async def _followup_and_tts(
    question: str, transcript: str, voice_id: str,
) -> tuple[str, str]:
    """Generate follow-up via Flash then TTS — runs in parallel with Gemma 4 eval.

    `voice_id` is the per-session voice from `voice_for_session(session.id)`
    — passed in (rather than recomputed here) to keep this helper a pure
    string-in / string-out function the caller can compose freely.
    """
    next_q = await generate_followup(question, transcript)
    audio_url = await synthesize_speech(next_q, voice_id=voice_id)
    return next_q, audio_url


# ── background evaluation ────────────────────────────────────────────────────

def _apply_eval_to_turn(turn: InterviewTurn, eval_out: EvaluatorOutput) -> None:
    """Copy evaluator output onto an InterviewTurn row (no commit)."""
    turn.directness_score  = eval_out.directness
    turn.star_score        = eval_out.star
    turn.specificity_score = eval_out.specificity
    turn.impact_score      = eval_out.impact
    turn.conciseness_score = eval_out.conciseness
    turn.delivery_score    = eval_out.delivery
    turn.feedback          = eval_out.notes
    turn.ai_model_used     = EVAL_MODEL
    turn.evaluated_at      = datetime.utcnow()


async def _run_background_eval(
    session_id: UUID,
    turn_id: UUID,
    question: str,
    transcript: str,
    history: list[dict],
    cv_summary: dict | None,
) -> None:
    """Evaluate a turn after the request has already returned, then persist.

    Runs in its own AsyncSession because the request-scoped session that
    spawned this task is closed by the time the response leaves the wire.
    Failures are swallowed (logged) per the "skip_and_log" policy: turn 1
    just keeps its null scores and the finalize aggregator drops it from
    the per-dim average. Always unregisters from the eval registry in the
    `finally` block so a missed finalize doesn't leak the Task reference.
    """
    try:
        async with AsyncSessionLocal() as db:
            try:
                eval_out = await evaluate_turn(
                    question, transcript, history, cv_summary=cv_summary,
                )
                turn = await db.get(InterviewTurn, turn_id)
                if turn is None:
                    logger.warning(
                        "Background eval: turn %s vanished before scores landed; "
                        "skipping write.",
                        turn_id,
                    )
                    return
                _apply_eval_to_turn(turn, eval_out)
                await db.commit()
                logger.info(
                    "Background eval complete for session=%s turn=%s",
                    session_id, turn_id,
                )
            except Exception:
                # Roll the half-applied transaction back, then re-raise so the
                # outer except logs the traceback. Without rollback the next
                # use of this session inside the same `async with` would
                # surface a confusing "current transaction is aborted" error.
                await db.rollback()
                raise
    except Exception:  # noqa: BLE001
        logger.exception(
            "Background eval failed for session=%s turn=%s; "
            "scores remain null and the turn will be excluded from the "
            "session aggregate.",
            session_id, turn_id,
        )
    finally:
        eval_registry.discard(session_id)


async def _await_background_eval(session_id: UUID) -> None:
    """If turn 1's eval is still running, wait for it before finalizing.

    Idempotent: returns immediately when no task is registered (e.g. the
    background task already finished and called `discard`, or the demo
    happens to be running on a worker that restarted between turns and
    lost the in-memory registry — the inline fallback in `submit_turn`
    handles the latter case).
    """
    task = eval_registry.pop(session_id)
    if task is None:
        return
    if task.done():
        return
    logger.info(
        "Finalize: waiting for background eval to finish for session=%s",
        session_id,
    )
    # The task itself swallows exceptions, so this await never raises.
    await task


# ── session-completion aggregation ────────────────────────────────────────────

# Per-turn score tuple shape used by the aggregator below:
# (directness, star, specificity, impact, conciseness, delivery, fillers)
# All score slots are nullable so that a turn whose background eval
# failed (or was never run) cleanly drops out of the per-dim averages.
_TurnScores = tuple[
    float | None, float | None, float | None,
    float | None, float | None, float | None,
    int,
]


def _per_dimension_averages(turns: list[_TurnScores]) -> dict[str, float | None]:
    """Average each rubric dimension independently across `turns`.

    Each dimension is filtered for non-null values BEFORE averaging so:
      * `delivery` is averaged only over turns where the candidate had the
        camera on (legacy behavior — webcam declined ⇒ null).
      * Any of the 5 base scores can also be null when a turn's background
        eval crashed or never ran. Such a turn contributes null for the
        affected dim but still counts for the others (it shouldn't
        normally — eval is all-or-nothing — but this keeps the aggregator
        robust to partial failure).

    Returns null for a dimension when no turn produced a score for it; the
    history chart drops the line entirely instead of plotting zeros.
    """
    def _avg(values: list[float | None]) -> float | None:
        non_null = [v for v in values if v is not None]
        return round(sum(non_null) / len(non_null), 2) if non_null else None

    return {
        "directness":  _avg([t[0] for t in turns]),
        "star":        _avg([t[1] for t in turns]),
        "specificity": _avg([t[2] for t in turns]),
        "impact":      _avg([t[3] for t in turns]),
        "conciseness": _avg([t[4] for t in turns]),
        "delivery":    _avg([t[5] for t in turns]),
    }


async def _upsert_session_metrics(
    db: AsyncSession,
    *,
    session_id: UUID,
    averages: dict[str, float | None],
    total_filler_word_count: int,
    overall_score: float | None,
    turns_evaluated: int,
) -> None:
    """Write (or replace) the cached aggregate row for a completed session.

    `session_metrics.session_id` has a UNIQUE constraint, so a re-finalize
    of the same session (shouldn't happen in the 2-turn flow but cheap
    insurance) deletes the existing row first rather than tripping IntegrityError.
    """
    existing = await db.execute(
        select(SessionMetrics).where(SessionMetrics.session_id == session_id)
    )
    row = existing.scalar_one_or_none()
    if row is not None:
        await db.delete(row)
        await db.flush()

    db.add(SessionMetrics(
        session_id=session_id,
        avg_directness=averages["directness"],
        avg_star=averages["star"],
        avg_specificity=averages["specificity"],
        avg_impact=averages["impact"],
        avg_conciseness=averages["conciseness"],
        avg_delivery=averages["delivery"],
        total_filler_word_count=total_filler_word_count,
        overall_score=overall_score,
        turns_evaluated=turns_evaluated,
    ))
    await db.flush()


@router.post("/{session_id}/turns", response_model=TurnSubmitOut)
async def submit_turn(
    session_id: UUID,
    audio: UploadFile = File(...),
    # Browser-computed webcam analytics (see `faceHeuristics.ts` on the
    # frontend). JSON-encoded; missing when the candidate declined camera.
    # Parse failures degrade gracefully to the 5-score path rather than 400.
    cv_summary: str | None = Form(None),
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> TurnSubmitOut:
    # 1. Load session — verify ownership.
    session = await db.get(InterviewSession, session_id)
    if not session or session.user_id != user.id:
        raise HTTPException(status_code=404, detail="Session not found")
    if session.status != SessionStatus.in_progress:
        raise HTTPException(status_code=400, detail="Session is not in progress")

    # 2. Find the current unanswered turn (question exists, transcript is NULL).
    result = await db.execute(
        select(InterviewTurn)
        .where(
            InterviewTurn.session_id == session_id,
            InterviewTurn.transcript_text.is_(None),
        )
        .order_by(InterviewTurn.turn_number)
        .limit(1)
    )
    current_turn = result.scalar_one_or_none()
    if current_turn is None:
        raise HTTPException(status_code=400, detail="No pending turn for this session")

    # 3. Transcribe.
    audio_bytes = await audio.read()
    transcript = await transcribe_audio(audio_bytes, audio.filename or "audio.webm")

    # 4. Filler words (regex ground truth per CLAUDE.md).
    filler_count, filler_breakdown = count_filler_words(transcript)

    # 5. Collect prior evaluated turns for history context.
    prior_result = await db.execute(
        select(InterviewTurn)
        .where(
            InterviewTurn.session_id == session_id,
            InterviewTurn.transcript_text.isnot(None),
        )
        .order_by(InterviewTurn.turn_number)
    )
    prior_turns = prior_result.scalars().all()
    history = [
        {"question": t.question_text, "transcript": t.transcript_text}
        for t in prior_turns
    ]

    # 6. Parse webcam analytics sidecar if present. Failing closed (None)
    # keeps the turn viable; the evaluator just skips the delivery score.
    parsed_cv_summary: dict | None = None
    if cv_summary:
        try:
            loaded = json.loads(cv_summary)
            if isinstance(loaded, dict):
                parsed_cv_summary = loaded
            else:
                logger.warning("cv_summary payload was not a JSON object; ignoring")
        except json.JSONDecodeError as exc:
            logger.warning("cv_summary JSON parse failed: %s", exc)

    # 7. Hardcoded 2-turn rule (CLAUDE.md): turn 2 is always final.
    is_final = current_turn.turn_number >= 2

    # 8a. Persist transcript + filler counts BEFORE doing any LLM work.
    #     For non-final turns the eval moves to a background task that
    #     mutates this same row; persisting now means it always finds a
    #     transcript to evaluate against and the row is durable even if
    #     the bg task crashes.
    current_turn.transcript_text       = transcript
    current_turn.cv_summary            = parsed_cv_summary
    current_turn.filler_word_count     = filler_count
    current_turn.filler_word_breakdown = filler_breakdown

    # 8b. Branch: non-final ⇒ scoring goes to background; final ⇒ inline.
    if not is_final:
        # Only wait for follow-up + TTS (~1-3s). Gemma 4 (~30-40s) is
        # spawned as a detached task that writes scores to the DB later.
        # Voice was resolved at session-create time and persisted on
        # `session.voice_id`, so turn 2's audio always sounds like the
        # same interviewer who asked turn 1 even after a refresh.
        # Legacy rows (created before the column existed) fall back to
        # the old deterministic-random derivation from session.id —
        # which would have given the same answer at session-create
        # time, so the behavior is unchanged for those rows too.
        turn_voice_id = session.voice_id or voice_for_session(session.id)
        next_q, next_audio_url = await _followup_and_tts(
            current_turn.question_text,
            transcript,
            turn_voice_id,
        )
        await _insert_followup_turn(db, session_id, current_turn.id, next_q)
        # Commit BEFORE registering the background task so the bg task's
        # fresh AsyncSession sees the persisted transcript on its first
        # query. Without this, there's a tiny race where the task could
        # start evaluating an empty transcript_text.
        await db.commit()

        bg_task = asyncio.create_task(
            _run_background_eval(
                session_id=session_id,
                turn_id=current_turn.id,
                question=current_turn.question_text,
                transcript=transcript,
                history=history,
                cv_summary=parsed_cv_summary,
            ),
            name=f"eval-session-{session_id}-turn-{current_turn.turn_number}",
        )
        eval_registry.register(session_id, bg_task)

        return TurnSubmitOut(
            transcript=transcript,
            scores=None,
            feedback=None,
            filler_word_count=filler_count,
            filler_word_breakdown=filler_breakdown,
            next_question=next_q,
            next_question_audio_url=next_audio_url,
            is_final=False,
            evaluation_pending=True,
        )

    # 8c. Final turn: evaluation must complete inline because we need its
    #     scores for the session aggregate. We also drain any pending
    #     background eval (turn 1's) before reading prior_turns so the
    #     aggregator sees the latest scores.
    eval_out = await evaluate_turn(
        current_turn.question_text, transcript, history,
        cv_summary=parsed_cv_summary,
    )
    _apply_eval_to_turn(current_turn, eval_out)

    # Drain turn 1's background eval (if any). Idempotent — no-op when
    # the bg task already completed and unregistered itself.
    await _await_background_eval(session_id)

    # Re-fetch prior turns AFTER awaiting the bg eval so we read its
    # newly-committed scores. Refresh through the ORM rather than
    # re-querying so identity-mapped rows already in this session pick
    # up the bg task's writes.
    for t in prior_turns:
        await db.refresh(t)

    # Inline fallback: if any prior turn still has no scores (e.g. the
    # bg task failed and we logged the error, OR the worker restarted
    # between turns and the task vanished), evaluate that turn here so
    # the session can still finalize. Per "skip_and_log" policy we don't
    # block finalization on a re-failure — we just log and move on.
    for t in prior_turns:
        if t.directness_score is not None:
            continue
        if t.transcript_text is None:
            continue
        logger.warning(
            "Inline-eval fallback for session=%s turn=%s "
            "(background eval missing or failed)",
            session_id, t.id,
        )
        try:
            inline_history = [
                {"question": p.question_text, "transcript": p.transcript_text}
                for p in prior_turns
                if p.id != t.id and p.transcript_text is not None
            ]
            inline_cv = t.cv_summary if isinstance(t.cv_summary, dict) else None
            inline_eval = await evaluate_turn(
                t.question_text, t.transcript_text, inline_history,
                cv_summary=inline_cv,
            )
            _apply_eval_to_turn(t, inline_eval)
        except Exception:  # noqa: BLE001
            logger.exception(
                "Inline-eval fallback also failed for session=%s turn=%s; "
                "this turn will be excluded from the session aggregate.",
                session_id, t.id,
            )

    # 9. Aggregate every turn that produced scores. Turns whose eval
    #    failed contribute None per dim and naturally drop out via
    #    `_per_dimension_averages`.
    all_turn_scores: list[_TurnScores] = [
        (
            float(t.directness_score)  if t.directness_score  is not None else None,
            float(t.star_score)        if t.star_score        is not None else None,
            float(t.specificity_score) if t.specificity_score is not None else None,
            float(t.impact_score)      if t.impact_score      is not None else None,
            float(t.conciseness_score) if t.conciseness_score is not None else None,
            float(t.delivery_score)    if t.delivery_score    is not None else None,
            int(t.filler_word_count or 0),
        )
        for t in prior_turns
    ] + [(
        float(eval_out.directness),
        float(eval_out.star),
        float(eval_out.specificity),
        float(eval_out.impact),
        float(eval_out.conciseness),
        float(eval_out.delivery) if eval_out.delivery is not None else None,
        filler_count,
    )]
    per_dim_avgs = _per_dimension_averages(all_turn_scores)
    total_fillers = sum(t[6] for t in all_turn_scores)
    # Overall: average of every populated dimension score across every
    # turn, scaled 0-10 → 0-100. Matches the prior behavior so existing
    # rows in `interview_sessions.overall_score` remain comparable.
    flat_scores = [
        v for t in all_turn_scores for v in t[:6] if v is not None
    ]
    # If literally every dim across every turn is null (catastrophic eval
    # failure on every turn), keep overall_score null rather than write
    # 0.0 — the history chart already handles null by dropping the point.
    overall: float | None
    if flat_scores:
        overall = min(99.99, round(sum(flat_scores) / len(flat_scores) * 10, 2))
    else:
        overall = None

    turns_evaluated = sum(
        1 for t in all_turn_scores if any(v is not None for v in t[:6])
    )

    session.status        = SessionStatus.completed
    session.ended_at      = func.now()
    session.overall_score = overall

    await _upsert_session_metrics(
        db,
        session_id=session_id,
        averages=per_dim_avgs,
        total_filler_word_count=total_fillers,
        overall_score=overall,
        turns_evaluated=turns_evaluated,
    )

    await db.commit()

    return TurnSubmitOut(
        transcript=transcript,
        scores=ScoresOut(
            directness=eval_out.directness,
            star=eval_out.star,
            specificity=eval_out.specificity,
            impact=eval_out.impact,
            conciseness=eval_out.conciseness,
            delivery=eval_out.delivery,
        ),
        feedback=eval_out.notes,
        filler_word_count=filler_count,
        filler_word_breakdown=filler_breakdown,
        next_question=None,
        next_question_audio_url=None,
        is_final=True,
        evaluation_pending=False,
    )


# ── history routes ───────────────────────────────────────────────────────────

# Hard cap on `GET /sessions` rows. The history page renders a chart + table
# inline, so paging UI is overkill for the demo — 50 most-recent completed
# sessions is well past anything a user will rack up during the hackathon.
_HISTORY_LIMIT = 50


def _averages_from_metrics(m: SessionMetrics | None) -> DimensionAverages:
    """Adapt the cached metrics row to the wire-format averages object."""
    if m is None:
        return DimensionAverages()
    return DimensionAverages(
        directness=m.avg_directness,
        star=m.avg_star,
        specificity=m.avg_specificity,
        impact=m.avg_impact,
        conciseness=m.avg_conciseness,
        delivery=m.avg_delivery,
    )


def _parse_company_summary(raw: str | None) -> CompanyBriefOut | None:
    """Decode the persisted JSON brief back into the wire-format model.

    Returns None on missing or malformed payloads so a single bad row in
    history doesn't 500 the whole detail screen.
    """
    if not raw:
        return None
    try:
        return CompanyBriefOut.model_validate_json(raw)
    except Exception as exc:  # noqa: BLE001
        logger.warning("company_summary parse failed: %s", exc)
        return None


@router.get("", response_model=list[SessionListItem])
async def list_sessions(
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> list[SessionListItem]:
    """Return the caller's completed sessions, newest first.

    Per-dimension averages are read from the cached `session_metrics` row
    populated when the session finalized. Sessions that finished BEFORE
    that cache existed (legacy rows) come back with all averages = null;
    the frontend chart simply skips them.
    """
    result = await db.execute(
        select(InterviewSession, SessionMetrics)
        .outerjoin(
            SessionMetrics,
            SessionMetrics.session_id == InterviewSession.id,
        )
        .where(
            InterviewSession.user_id == user.id,
            InterviewSession.status == SessionStatus.completed,
        )
        .order_by(InterviewSession.created_at.desc())
        .limit(_HISTORY_LIMIT)
    )
    rows: list[SessionListItem] = []
    for session, metrics in result.all():
        rows.append(SessionListItem(
            id=session.id,
            company=session.company,
            job_title=session.job_title,
            status=session.status.value,
            overall_score=session.overall_score,
            started_at=session.started_at,
            ended_at=session.ended_at,
            created_at=session.created_at,
            turns_evaluated=metrics.turns_evaluated if metrics else 0,
            total_filler_word_count=(
                metrics.total_filler_word_count if metrics else None
            ),
            averages=_averages_from_metrics(metrics),
        ))
    return rows


@router.get("/{session_id}", response_model=SessionDetailOut)
async def get_session(
    session_id: UUID,
    user: User = Depends(get_current_user_db),
    db: AsyncSession = Depends(get_db),
) -> SessionDetailOut:
    """Full session payload: session row + ordered turns + cached metrics.

    Ownership check happens BEFORE we fetch turns so an unauthorized
    request can't probe for another user's row counts via timing.
    """
    session = await db.get(InterviewSession, session_id)
    if session is None or session.user_id != user.id:
        raise HTTPException(status_code=404, detail="Session not found")

    turns_result = await db.execute(
        select(InterviewTurn)
        .where(InterviewTurn.session_id == session_id)
        .order_by(InterviewTurn.turn_number)
    )
    turns = turns_result.scalars().all()

    metrics_result = await db.execute(
        select(SessionMetrics).where(SessionMetrics.session_id == session_id)
    )
    metrics = metrics_result.scalar_one_or_none()

    turn_outs = [
        TurnOut(
            id=t.id,
            turn_number=t.turn_number,
            question_text=t.question_text,
            transcript_text=t.transcript_text,
            is_followup=t.is_followup,
            scores=ScoresOut(
                # `0` is a valid evaluator score; coerce nulls to 0 only for
                # turns that haven't been evaluated yet (transcript is null).
                # An evaluated turn always has all 5 base scores populated.
                directness=int(t.directness_score or 0),
                star=int(t.star_score or 0),
                specificity=int(t.specificity_score or 0),
                impact=int(t.impact_score or 0),
                conciseness=int(t.conciseness_score or 0),
                delivery=(
                    int(t.delivery_score) if t.delivery_score is not None else None
                ),
            ),
            feedback=t.feedback,
            filler_word_count=t.filler_word_count or 0,
            filler_word_breakdown=t.filler_word_breakdown or {},
            evaluated_at=t.evaluated_at,
            created_at=t.created_at,
        )
        for t in turns
    ]

    return SessionDetailOut(
        id=session.id,
        company=session.company,
        job_title=session.job_title,
        status=session.status.value,
        overall_score=session.overall_score,
        started_at=session.started_at,
        ended_at=session.ended_at,
        created_at=session.created_at,
        summary=_parse_company_summary(session.company_summary),
        turns=turn_outs,
        averages=_averages_from_metrics(metrics),
        total_filler_word_count=(
            metrics.total_filler_word_count if metrics else None
        ),
        turns_evaluated=metrics.turns_evaluated if metrics else 0,
    )
